import * as animacaoSobre from '/Scripts/SobreAnimacao.js'
import * as animacaoEstudos from '/Scripts/EstudosAnimacao.js'
import * as animacaoProjetos from '/Scripts/ProjetosAnimacao.js'
import * as animacaoAfazeres from '/Scripts/AfazeresAnimacao.js'
import * as animacaoSkills from '/Scripts/SkillsAnimacao.js'